// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1760356426);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1760356786);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1760356666);
user_pref("app.update.lastUpdateTime.region-update-timer", 1760360386);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1760357026);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1760356906);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1760356306);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1760357146);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1760356546);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f37c6e76-04e3-4b88-a499-3036d78356d2}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.downloads-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1744107684);
user_pref("browser.laterrun.bookkeeping.sessionCount", 12);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"6805432266727075\":1760356281010,\"1089127335217754\":1760356281023,\"5089304167837298\":1760356281035}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{fe9d4390-af6c-42b1-b616-ba791aff8b31}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1760360387);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1760369272622");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1760371050622");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1760357307266");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1760378907266");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230309232128");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1760356279");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230309232128");
user_pref("browser.startup.homepage_override.mstone", "111.0");
user_pref("browser.startup.lastColdStartupCheck", 1760356277);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1744108083495");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "111.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "f21b7096ccdb49ac9c1762ce40f384a5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1760356426);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230309232128");
user_pref("extensions.lastAppVersion", "111.0");
user_pref("extensions.lastPlatformVersion", "111.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a2b3375d-de62-419b-a546-f99b5e10aa42\",\"pictureinpicture@mozilla.org\":\"4daef5a0-d488-4b76-be20-03569f30305b\",\"screenshots@mozilla.org\":\"3e4e8fd2-885c-4f21-aa82-510b04be40d9\",\"webcompat-reporter@mozilla.org\":\"237311ca-24d1-4211-ba4b-6e43a92ac77c\",\"webcompat@mozilla.org\":\"3a1737bc-f2f7-4076-b86a-d0c65891a6c3\",\"default-theme@mozilla.org\":\"2c81cb0d-5468-44de-8785-adb50861e37b\",\"addons-search-detection@mozilla.com\":\"a3ea114f-acfc-4a8e-962f-8a3ceda48129\",\"google@search.mozilla.org\":\"9e57a13a-c197-4a85-b4f4-a0bb628a5f64\",\"wikipedia@search.mozilla.org\":\"ae05a898-428f-408c-9bd6-7e46c55fea3f\",\"bing@search.mozilla.org\":\"6fd5396b-792a-4ee7-a5b3-1892aa007bd2\",\"ddg@search.mozilla.org\":\"b8239a62-1917-4548-acea-64e6e5c3e4b0\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1760357139);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastDownload", 1744107914);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1744107908);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1744107914);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20230309232128");
user_pref("media.gmp-manager.lastCheck", 1760356372);
user_pref("media.gmp-manager.lastEmptyCheck", 1760356372);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1760357140);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1760357141435");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d297ae1a-3a02-4768-b957-bb292f7c10ba");
user_pref("services.settings.clock_skew_seconds", 2111);
user_pref("services.settings.last_update_seconds", 1760367461);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1760367461);
user_pref("services.settings.main.devtools-devices.last_check", 1760367461);
user_pref("services.settings.main.hijack-blocklists.last_check", 1760367461);
user_pref("services.settings.main.language-dictionaries.last_check", 1760367461);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1745201869);
user_pref("services.settings.main.password-recipes.last_check", 1760367461);
user_pref("services.settings.main.sites-classification.last_check", 1760367461);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1760357139);
user_pref("toolkit.startup.last_success", 1760356274);
user_pref("toolkit.telemetry.cachedClientID", "dca096a9-7ef5-490a-85c7-0574a978d219");
user_pref("toolkit.telemetry.previousBuildID", "20230309232128");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
